
output: continuous

seed: 0
num_repeats: 5
sensitive_predictor: False

models:
  FGLM:
    param:
      lam: [1e-3, 10., 11]
    log_exp_grid: True
  GLM:
    param:
      lam: [0., 0., 0]
    log_exp_grid: False
  CFGLM:
    param:
      lam: [1e-3, 10., 11]
      phi: [1e-3, 1e-3, 1]
    log_exp_grid: True
  CFGLM1:
    param:
      lam: [1e-3, 10., 11]
      phi: [0.1, 0.1, 1]
    log_exp_grid: True
  CFGLM2:
    param:
      lam: [1e-3, 10., 11]
      phi: [0.2, 0.2, 1]
    log_exp_grid: True