
output: continuous

seed: 0
num_repeats: 2
sensitive_predictor: False

models:
  FGLM:
    param:
      lam: [1e-3, 6., 11]
    log_exp_grid: True
  GLM:
    param:
      lam: [0., 0., 0]
    log_exp_grid: False